serve:
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:5173
      allowed_methods: [GET, POST, PUT, PATCH, DELETE]
      allow_credentials: true
  api:
    port: 4456

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/access-rules.json

errors:
  fallback:
    - json

authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

authorizers:
  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User-Id: "{{ print .Subject }}"
        X-User-Email: "{{ print .Extra.identity.traits.email }}"
